### ISSUE TITLE
Support timeout.refresh in node environments

### ISSUE THREAD

**Issue by SimenB** [sinonjs/fake-timers#187]
* Lolex version : 2.6.0
* Environment   : Node.js macOS
* Example URL   : N/A
* Other libraries you are using: N/A

**What did you expect to happen?**
`clock.setTimeout(() => {}, 0).refresh` should exist.

(as it's not released I didn't _really_ expect that, but y'know.)

See https://github.com/nodejs/node/pull/20298, which is slated to land in 10.2.0.

**What actually happens**
It's not there

**How to reproduce**
Create a clock in a node env, call `setTimeout`, observe missing `refresh` function on return value.

**Comment by benjamingr** [comment]
So basically it should do `clearTimeout and then setTimeout`?

**Comment by SimenB** [comment]
Yeah, I think that makes sense.

Have to keep around old timeouts as well, but maybe that's done already? Keeping a weak reference might be overkill

**Comment by benjamingr** [comment]
@SimenB do you feel like making a PR?


Otherwise - I might have time to take a look at this when I'm back from the Node.js summit.

**Comment by benjamingr** [comment]
This was fixed in https://github.com/sinonjs/lolex/pull/193 🎉

**Comment by SimenB** [comment]
The function was added, but it has no logic. Should it?

**Comment by benjamingr** [comment]
@SimenB technically it probably should (even if through just a clearTimeout and setTimeout) - but I doubt anyone is going to use the two features together for some time. I can reopen if you'd like.

**Comment by jpenglert** [comment]
@SimenB I have an existing test that broke when I refactored from clearTimeout()/setTimeout() to Timer.refresh() because the fake Timer.refresh() does not call clearTimeout()/setTimeout(). Any plans to add that logic?

**Comment by SimenB** [comment]
PR very much welcome 🙂

**Comment by SimenB** [comment]
I'll reopen this since we don't actually support it, it's just a noop

**Comment by benjamingr** [comment]
Fixed in https://github.com/sinonjs/fake-timers/pull/328 , we need a release, it'll be a few days before I'll be in front of a computer with npm credentials.
