### ISSUE TITLE
Provide more context on infinites recursion

### ISSUE THREAD

**Issue by SimenB** [sinonjs/fake-timers#230]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Lolex version : 3.0
* Environment   : N/A
* Example URL   : N/A
* Other libraries you are using: N/A

**What did you expect to happen?**

See https://github.com/facebook/jest/issues/2893 for details.

Tl;dr: Right now Lolex just throws an error if it thinks we're in an infinite loop of timers (timers scheduling new timers). This comes from here: https://github.com/sinonjs/lolex/blob/29b4ecc8bd186584ab4139341f3128a4349463ba/lolex.js#L210

It would be nice if the message thrown included a stack trace back to the code actually scheduling timers

**What actually happens**

An error without context

**How to reproduce**
https://runkit.com/embed/jqyax6pkc5bq

**Comment by benjamingr** [comment]
We can add the stack to clocks when they are captured and show it on the clock when this is thrown - though this will be _really_ expensive CPU wise.

**Comment by SimenB** [comment]
What about, after reaching `loopLimit`, you schedule 10 more or so, and capture just their stacks, then throw? So in the normal case there is no change, but you loop a few extra times (maybe even `loopLimit - 10` to not really affect anything observable) in the case where things are gonna throw anyways?

**Comment by benjamingr** [comment]
So:

 - If I'm inside lolex and I'm at `loopLimit - 10`
 - Then start capturing stack traces when setTimeout/setInterval etc are called
 - If the loop limit is reached before another timer is hit, fail without a stack
 - Otherwise fail with the stack any of those timers.

Sounds useful/good to me and like it should solve the 95% case.

**Comment by SimenB** [comment]
Yeah, that sounds reasonable to me! Potentially start with just a single stack instead of 10, not sure? Changing that threshold is simple once the logic is in place though, so not something we need to spend time on deciding now

**Comment by SimenB** [comment]
>* If the loop limit is reached before another timer is hit, fail without a stack

Wait, no - not this. If `loopLimit` is 100, we don't want to fail if we get to 95 timers before bailing

**Comment by alistairjcbrown** [comment]
Put up PR #325 to add stack trace output for the next excess job to be run - let me know if you think that's the right direction for solving this issue
