### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by szmarczak** [sinonjs/fake-timers#252]
It would be nice to have some events:

- `newTimer`
- `removeTimer`
- ...

It would for example allow to execute all new timers by:

```js
clock.on('newTimer', () => {
	clock.runAll();
});
```

**Comment by fatso83** [comment]
That would imply using the async interface, right, so the naming should probably reflect that. Such a trigger would be quite confusing in sync lolex code, I think.

**Comment by szmarczak** [comment]
Not stale

**Comment by fatso83** [comment]
@szmarczak This is a nice feature, but from experience, you have a much higher chance of seeing it implemented if you do an attempt yourself and provide a pull request :-) The lolex source code is quite simple, short and easy to get into.

**Comment by szmarczak** [comment]
Yeah, I'll do when I have more free time. Currently I'm focused on HTTP/2 support in Got.
