### ISSUE TITLE
install() throws if setImmediate/clearImmediate is set in config.toFake if `_global.setImmediate` does not exist

### ISSUE THREAD

**Issue by SanderDeWaal1992** [sinonjs/fake-timers#277]
* Lolex version : 5.1.1
* Environment   : Chrome

**What did you expect to happen?**

That 'setImmediate' and 'clearImmediate' would be ignored if you pass them to config.toFake if `_global.setImmediate` does not exist since there is nothing to fake for them.

**What actually happens**

It works in node, but it does not work in Chrome (were setImmediate is not available). In that case it throws:
```
TypeError: Cannot set property 'hadOwnProperty' of undefined
            at hijackMethod (.../lolex.js:529:1)
            at Object.install (.../lolex.js:1265:1)
```

**How to reproduce**
```
lolex.install({ now: 0, toFake: [
            "setImmediate", "clearImmediate",
            /** and others: */
            "setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date", "nextTick", "hrtime"
]});
```

**Comment by fatso83** [comment]
Thank you for this. This seems like a valid case to check for. Want to try and have a go at fixing it? We ❤️  pull requests :)

**Comment by fatso83** [comment]
Seems fixed a long time ago
```
carlerik at ubuntu-i9-vm in /tmp/a 
$ node test.js 

carlerik at ubuntu-i9-vm in /tmp/a 
$ cat test.js 
const lolex = require('@sinonjs/fake-timers')
lolex.install({ now: 0, toFake: [
            "setImmediate", "clearImmediate",
            /** and others: */
            "setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date", "nextTick", "hrtime"
]});
```
