### ISSUE TITLE
Error: Cannot clear timer: timer created with setInterval() but cleared with clearTimeout()

### ISSUE THREAD

**Issue by slightlytwisted** [sinonjs/fake-timers#304]
* FakeTimers version : latest release
* Environment   : NodeJS 12.13.0

fake-timers should not assert that calls to `clearTimer()` be passed only timers created by `createTimer()` and that calls to `clearInterval()` be passed only timers created by `createInterval()` because the [HTML Living Standard](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-setinterval) indicates that:

> Because clearTimeout() and clearInterval() clear entries from the same list, either method can be used to clear timers created by setTimeout() or setInterval().

The [assertion](https://github.com/sinonjs/fake-timers/blob/0beb3c3bd328570c6fbde0e32604ca005e2cc331/src/fake-timers-src.js#L457) in fake-timer should probably be relaxed.

**Comment by fatso83** [comment]
Love a bug report with a WHATWG link to the reference ❤️

**Comment by itayperry** [comment]
Hey everyone, I'm taking a look at this :)

**Comment by itayperry** [comment]
A question :) This `clearTimer()` function appears in 2 different files, why is that? Should I change it in both files? I would love for some help. 

- First location: https://github.com/sinonjs/fake-timers/blob/7f8322effa73a94dc43896cdfb49d63e821b32d1/fake-timers.js#L1733
- Second location: https://github.com/sinonjs/fake-timers/blob/7f8322effa73a94dc43896cdfb49d63e821b32d1/src/fake-timers-src.js#L429

**Comment by benjamingr** [comment]
@itayperry fake-timers is generated from fake-timers-src through bundling it: https://github.com/sinonjs/fake-timers/blob/7f8322effa73a94dc43896cdfb49d63e821b32d1/package.json#L24 - you should generally only need to edit fake-timers-src.

**Comment by itayperry** [comment]
All ready and tested :) 
I hope this solves the issue properly.
#324

**Comment by benjamingr** [comment]
Fixed in https://github.com/sinonjs/fake-timers/pull/324/commits/1f83b99639f57a3980847da7aaddcf3d11308b5d

**Comment by NearHuscarl** [comment]
In the mean time, I've got my test working again by patching the code from the commit mentioned above using [`patch-package`](https://github.com/ds300/patch-package). Here is the instructions for anyone wants to do the same

* Open this file `node_modules/@sinonjs/fake-timers/src/fake-timers-src.js` and patch [this code](https://github.com/sinonjs/fake-timers/commit/1f83b99639f57a3980847da7aaddcf3d11308b5d#diff-41a23d75048c36f3649e9fea5cd63cab3d94802c03bc6df0fdc009847d786bf1R447-R451)
* Run the following command

```
npx patch-package @sinonjs/fake-timers
```

After that, there should be a new file at `patches/@sinonjs+fake-timers+6.0.1.patch` with the following content

```diff
diff --git a/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js b/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js
index f723db5..7cdd059 100644
--- a/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js
+++ b/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js
@@ -444,7 +444,11 @@ function withGlobal(_global) {
         if (clock.timers.hasOwnProperty(id)) {
             // check that the ID matches a timer of the correct type
             var timer = clock.timers[id];
-            if (timer.type === ttype) {
+            if (
+              timer.type === ttype ||
+              (timer.type === "Timeout" && ttype === "Interval") ||
+              (timer.type === "Interval" && ttype === "Timeout")
+            ) {
                 delete clock.timers[id];
             } else {
                 var clear =
````

**Comment by tapz** [comment]
How do I disable this functionality completely? I just want to mock dates and now face timers give an error with node pg, which is not my code. So I need to use something else than sinonjs because it has this kind of side effects.

**Comment by fatso83** [comment]
@tapz Are you running 7.0.1? Cause this was released yesterday and includes the fix for this issue. Not sure how it applies to your case, as I have no idea what you are talking about (way too inspecific), but I would try to `npm install @sinonjs/fake-timers@latest`.

**Comment by benjamingr** [comment]
@tapz you can `.install` with a parameter indicating what to fake - and you can just _not_ mock timers and only mock date.
