### ISSUE TITLE
"module" field doesn't point at a module

### ISSUE THREAD

**Issue by 43081j** [sinonjs/fake-timers#317]
When used as an es module via the "module" property and a bundler, we get no exports.

The sources, and the commonjs output are individual exports, such as:

```js
module.exports.install = fn;
// means:
const {install} = require('@sinonjs/fake-timers');
```

However, the browserify output results in an empty export:

```ts
import {install} from '@sinonjs/fake-timers';  // ERRORS
import * as timers from '@sinonjs/fake-timers'; // this is how it should be but is {} at the minute
import fakeTimers from '@sinonjs/fake-timers'; // ERRORS, no default export
timers.install; // DOESNT EXIST
```

the problem here seems to be that `"module"` in package.json should point at an ES module, but clearly doesn't. it instead points at a browserify bundle.. which is rather dated and will not work as expected in bundlers which interpret the `"module"` field.

**Comment by 43081j** [comment]
one solution is to add an `esm.js` file so we can `import {install} from '@sinonjs/fake-timers/esm'`.

which is just a small file that imports the default and re-exports correctly...

@fatso83 what do you think?

**Comment by mantoni** [comment]
For Sinon we solved this by generating a separate esm module in the `build.js` script:

https://github.com/sinonjs/sinon/blob/d2b4b726529f167d908747d2173b5491794ac718/build.js#L61-L80

The `module` field in `package.json` points to this module. We'd need to the same for `fake-timers` to fix this.
