### ISSUE TITLE
Date.now() cannot be faked when using @babel/runtime-corejs*

### ISSUE THREAD

**Issue by todofixthis** [sinonjs/fake-timers#321]
* FakeTimers version : 6.0.1
* Environment : node v10.19.0, macOS v10.15.4
* Example URL: 
* Other libraries you are using: See below.

# What did you expect to happen?
`Date.now()` returns 0

# What actually happens
`Date.now()` returns current timestamp.

# How to reproduce
1. Configure project to use `@babel/runtime-corejs3`:

    <details>
      <summary>package.json</summary>

      ```json
      {
        "name": "test",
        "version": "1.0.0",
        "description": "",
        "main": "index.js",
        "scripts": {
          "test": "echo \"Error: no test specified\" && exit 1"
        },
        "author": "",
        "license": "ISC",
        "devDependencies": {
          "@babel/core": "^7.9.0",
          "@babel/plugin-transform-runtime": "^7.9.0",
          "@babel/preset-env": "^7.9.0",
          "@babel/register": "^7.9.0"
        },
        "dependencies": {
          "@babel/runtime": "^7.9.2",
          "@babel/runtime-corejs3": "^7.9.2",
          "@sinonjs/fake-timers": "^6.0.1"
        }
      }
      ```
    </details>

    <details>
      <summary>babel.config.js</summary>

      ```js
      {
        "presets": ["@babel/preset-env"],
        "plugins": [
          ["@babel/plugin-transform-runtime", { "corejs": 3 }]
        ]
      }
      ```
    </details>

2. Create `index.js` as follows:
    ```js
    import FakeTimers from '@sinonjs/fake-timers'

    FakeTimers.install()

    console.log(new Date().getTime())
    console.log(Date.now())
    ```

3. Execute the script:
    ```bash
    > node -r @babel/register index.js
    0
    1585877900883
    ```

The last line of output should be `0`, but it is the current timestamp instead.

Note: can also be reproduced using (deprecated) `@babel/runtime-corejs2`.

**Comment by fatso83** [comment]
There is nothing per se that is saying `fake-timers` is to blame here, given that transpilers can do all sorts of things. I am guessing this has something to do with what `global` is detected to be. Is there, for instance, a `window` global from somewhere? If this is what is causing it, then you can use the `target` prop to work around it. This is an example from the readme:

```javascript
var FakeTimers = require("@sinonjs/fake-timers");
var context = {
    setTimeout: setTimeout // By default context.setTimeout uses the global setTimeout
}
var clock = FakeTimers.install({target: context});

context.setTimeout(fn, 15); // Schedules with clock.setTimeout

clock.uninstall();
// context.setTimeout is restored to the original implementation
```

Here, `context` would be `global.window` or something else that might be messing up the state of things. Could you interactively inspect the environment for weird stuff?

**Comment by fatso83** [comment]
Screw that. I decided to just run your test case (very easy to do, so great job, btw!) and I had misunderstood what was going on: fake timers ARE being installed, it seems, it's just that it does not seem to be working for that _one_ call. The other is fine. I'll inspect.

**Comment by fatso83** [comment]
OK, this was easy. Just run babel to inspect the output and it is immediatly clear:

javascript
```
$(npm bin)/babel index.js 
"use strict";

var _interopRequireDefault = require("@babel/runtime-corejs3/helpers/interopRequireDefault");

var _now = _interopRequireDefault(require("@babel/runtime-corejs3/core-js-stable/date/now"));

var _fakeTimers = _interopRequireDefault(require("@sinonjs/fake-timers"));

_fakeTimers["default"].install();

console.log(new Date().getTime());
console.log((0, _now["default"])());
```

You corejs3 is replacing `Date.now` by a strictly bound reference to `@babel/runtime-corejs3/core-js-stable/date/now`. We cannot do anything about that, basically, but maybe you can find a way to configure core-js to not do this.

**Comment by fatso83** [comment]
You can see others being bit by this exact issue: https://github.com/zeit/next.js/issues/7050.

I spent ten minutes looking into how `core-js` can be configured via babel's own configs for [transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) and [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env), but could not really find anything useful. `core-js` itself says it can be configured to [be less aggressive](https://github.com/zloirock/core-js#configurable-level-of-aggressiveness), so you might need to dig deeper.

**Comment by todofixthis** [comment]
Thanks for looking into this @fatso83 !  I'll dive a bit deeper and see if I can come up with something interesting 😺

**Comment by todofixthis** [comment]
Just now coming up for air, and I'm as stumped as you are.  I suspect that `@babel/plugin-transform-runtime` simply doesn't provide enough configurability, and the only option (aside from not using `Date.now()` 😁 ) would be to include `core-js` directly.

But, [I posted on Stackoverflow](https://stackoverflow.com/q/61020746/5568265), just in case 😺
