### ISSUE TITLE
Need new release

### ISSUE THREAD

**Issue by fristedt** [sinonjs/fake-timers#337]
Our project needs a fix introduced in June (https://github.com/sinonjs/fake-timers/issues/304), but the latest release was made in March.

When are you planning on making a new release?

**Comment by benjamingr** [comment]
@fatso83 - can you make a release? Otherwise I can try doing one but I never did one before for fake-timers.

We can also set up releases to happen from the CI so they are more frequent

**Comment by fatso83** [comment]
Having automated CI releases would be a good thing. We just need to be strict about semantic versioning wrt labels on merged issues.  I won't be leading any effort, though; just back from a 5-months code hiatus, so I'm a bit rusty.

I'll see if I can get to making a release this weekend. It's just a matter of following some steps in a markdown file and it's done in a few minutes. Only thing is that I consistently forget pushing the tag afterwards 🤦

**Comment by fatso83** [comment]
A [recent dependency update](https://github.com/sinonjs/fake-timers/commit/38a90303e3d1f51e5d3c9216b0d0c1a570229f4d) broke our builds on Safari, IE and Firefox, so I need to revert that first.

**Comment by fatso83** [comment]
@benjamingr This build broke when #325 was merged in June. It has been broken since. This blocks creating a new release. See details in https://github.com/sinonjs/fake-timers/pull/325#issuecomment-691995306

**Comment by fatso83** [comment]
@benjamingr Morgan [cut a new release](https://github.com/sinonjs/fake-timers/blob/master/CHANGELOG.md#700--2021-01-12) so this should close.
