### ISSUE TITLE
Incompatible with promise-polyfill (a solution included)

### ISSUE THREAD

**Issue by Finesse** [sinonjs/fake-timers#363]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

-   FakeTimers version : 7.0.2
-   Environment : Internet Explorer 11 with promise-polyfill

I make tests that run in different browsers (including IE 11) via Karma. IE doesn't support promises, so I include [promise-polyfill](https://github.com/taylorhakes/promise-polyfill). The following test case doesn't proceed in IE 11:

```bash
npm install @sinonjs/fake-timers@7.0.2 promise-polyfill@8.2.0 jasmine@3.6.4
```

```js
include 'promise-polyfill/src/polyfill';
import * as fakeTimers from '@sinonjs/fake-timers';

it('mocks time', async () => {
  const clock = fakeTimers.install();

  try {
    const delayCall = (callback) => {
      new Promise((resolve) => setTimeout(resolve, 2000))
        .then(callback)
        .then(() => delayCall(callback));
    };

    const callback = jasmine.createSpy();
    delayCall(callback);
    await clock.tickAsync(10500); // Never resolves
    expect(callback.calls.count()).toBe(5);
  } finally {
    clock.uninstall();
  }
});
```

(Jasmine isn't required, any test runner can be used)

The promise polyfill [uses the global `setImmediate` function](https://github.com/taylorhakes/promise-polyfill/blob/53729a381f70a3051f9cca75d4b4f2d232b980ca/src/index.js#L243), the fake-timers library [mocks the `setImmediate` function](https://github.com/sinonjs/fake-timers/blob/43dc8db9b0d67e6b0a4252b2aa8e448d999bfb8d/src/fake-timers-src.js#L787) and [uses `Promise` inside `tickAsync`](https://github.com/sinonjs/fake-timers/blob/43dc8db9b0d67e6b0a4252b2aa8e448d999bfb8d/src/fake-timers-src.js#L987). What happens is that `tickAsync` [calls `resolve`](https://github.com/sinonjs/fake-timers/blob/43dc8db9b0d67e6b0a4252b2aa8e448d999bfb8d/src/fake-timers-src.js#L990) that [calls the mocked `setImmediate`](https://github.com/taylorhakes/promise-polyfill/blob/53729a381f70a3051f9cca75d4b4f2d232b980ca/src/index.js#L50) that doesn't resolve because fake-timers has locked it, i.e. fake-timers dead-locks itself.

If I disable mocking `setImmediate` using the `toFake` parameter, the `callback` will be called only 1 time instead of 5. It happens because the promise inside `delayCall` gets resolved after `tickAsync` decides to exit, because `delayCall` resolves several promises sequentially while `tickAsync` waits for new timers only during [a single `originalSetTimeout` resolution](https://github.com/sinonjs/fake-timers/blob/43dc8db9b0d67e6b0a4252b2aa8e448d999bfb8d/src/fake-timers-src.js#L903). Since both `Promise` and `originalSetTimeout` wait using `setImmediate`, `tickAsync` exists before `delayCall` spawns a new timer. A solution is to make `originalSetTimer` wait longer than any number of promise-polyfill's [_immediateFn](https://github.com/taylorhakes/promise-polyfill/blob/53729a381f70a3051f9cca75d4b4f2d232b980ca/src/index.js#L238) calls. It can be achieved by implementing [`originalSetTimeout`](https://github.com/sinonjs/fake-timers/blob/43dc8db9b0d67e6b0a4252b2aa8e448d999bfb8d/src/fake-timers-src.js#L637) with `setTimeout` instead of `setImmediate` (because `setImmediate` always resolves before any `setTimeout`).

The ideal solution for all `toFake` values is to make `promise-polyfill` always use the original `setImmediate` and fake-timers to implement `originalSetTimeout` using `setTimeout` only. If you agree with this change and want me to make a MR, let me know. I'll  make an issue in the `promise-polyfill` repository for this change.

**At the moment I can fix the issue locally** in my project by disabling `setImmediate` individually for fake-timers. It will both disable mocking `setImmediate` and will make `originalSetTimeout` not use `setImmediate`. The fix in my code example:

```js
include 'promise-polyfill/src/polyfill';
import * as fakeTimers from '@sinonjs/fake-timers';

it('mocks time', async () => {
  // Remove setImmediate and then return back
  const originalProperty = Object.getOwnPropertyDescriptor(window, 'setImmediate');
  Object.defineProperty(window, 'setImmediate', { configurable: true, value: undefined });
  let fixedFakeTimers;
  try {
    fixedFakeTimers = fakeTimers.withGlobal(window);
  } finally {
    if (originalProperty) {
      Object.defineProperty(window, 'setImmediate', originalProperty);
    } else {
      delete window.setImmediate;
    }
  }

  const clock = fixedFakeTimers.install();

  try {
    const delayCall = (callback) => {
      new Promise((resolve) => setTimeout(resolve, 2000))
        .then(callback)
        .then(() => delayCall(callback));
    };

    const callback = jasmine.createSpy();
    delayCall(callback);
    await clock.tickAsync(10500); // Resolves quickly
    expect(callback.calls.count()).toBe(5);
  } finally {
    clock.uninstall();
  }
});
```

**Comment by benjamingr** [comment]
Opened a promise-polyfill PR: https://github.com/taylorhakes/promise-polyfill/pull/125

**Comment by benjamingr** [comment]
Looks like my PR was merged into promise-polyfill so I'll go ahead and close this :)

**Comment by Finesse** [comment]
@benjamingr Amending promise-polyfill isn't enough. This is also required:

> ... and fake-timers to implement `originalSetTimeout` using `setTimeout` only

This way fake-timers won't race with promise-polyfill
