### ISSUE TITLE
fake-timers 7 doesn't seem to forward setTimeout args

### ISSUE THREAD

**Issue by ronag** [sinonjs/fake-timers#368]
```js
setTimeout((foo) => {
  console.log(foo) // should log "hello"
}, 1, 'hello')
```

Refs: https://github.com/nodejs/undici/pull/675#issuecomment-812918698

**Comment by benjamingr** [comment]
@ronag hey - the args are just stored https://github.com/sinonjs/fake-timers/blob/master/src/fake-timers-src.js#L785 and then just applied to the args https://github.com/sinonjs/fake-timers/blob/master/src/fake-timers-src.js#L471 

Any chance I could get a quick repro? The example in your code seems to work:

```js
const fakeTimers = require('@sinonjs/fake-timers');

const clock = fakeTimers.install();

setTimeout((foo) => {
  console.log(foo) // this logs "hello"
}, 1, 'hello')

clock.tick(1);
```

**Comment by ronag** [comment]
I'll dig into it further. We had to pin in undici.

**Comment by benjamingr** [comment]
Thanks, probably a good-first-issue for people to debug and figure out in unidici :)

**Comment by ronag** [comment]
@dnlup FYI

**Comment by dnlup** [comment]
> @ronag hey - the args are just stored https://github.com/sinonjs/fake-timers/blob/master/src/fake-timers-src.js#L785 and then just applied to the args https://github.com/sinonjs/fake-timers/blob/master/src/fake-timers-src.js#L471
> 
> Any chance I could get a quick repro? The example in your code seems to work:
> 
> ```js
> const fakeTimers = require('@sinonjs/fake-timers');
> 
> const clock = fakeTimers.install();
> 
> setTimeout((foo) => {
>   console.log(foo) // this logs "hello"
> }, 1, 'hello')
> 
> clock.tick(1);
> ```

Thanks, @benjamingr . Could it be something related to the interaction with `nextTick` or similar? [This](https://github.com/nodejs/undici/blob/main/lib/client.js#L534) is the only instance that gives us problems in [this test](https://github.com/nodejs/undici/blob/main/test/request-timeout.js#L43). Before calling `setTimeout`, `this` is indeed not `undefined`, but when it is referenced inside the callback, it is.

**Comment by fatso83** [comment]
I would set a breakpoint in the fake timers code to have a look at the arguments at the point they are applied. Debugging unknown client code is kind of costly, and `this` reference problems are usually a point in client code, so I am not all that inclined into digging into this right now. Still, if `this` is defined at the point of calling, I do not see why it should change underway, as the object `this` references should be treated just the same as any other argument, so this is a bit strange.

**Comment by ronag** [comment]
Just to be clear there are no problems in v6. The problem only happens in v7.

**Comment by fatso83** [comment]
Ooh! That was totally new to me.

**Comment by benjamingr** [comment]
Sounds like a fun bug. Debugging is relatively straightforward (run with `--inspect-brk` and step into the fake-timers code which is a single pretty readable file)

**Comment by benjamingr** [comment]
(and run jest in band (--runInBand) if using jest because jest does very "creative" stuff)

**Comment by dnlup** [comment]
Thanks for all the feedback, I'll try to inspect it and get back to you.

**Comment by dnlup** [comment]
Could it be the `refresh` logic?

* https://github.com/sinonjs/fake-timers/blob/master/src/fake-timers-src.js#L364

It looks like the extra arguments are lost here, or am I missing something?

**Comment by fatso83** [comment]
@dnlup That seems like a good candidate! I agree with you. This seems like losing arguments.

**Comment by dnlup** [comment]
I can confirm that adding:

```js
 setTimeout(timer.func, timer.delay, ...timer.args);
```

on that line resolves our issue.

**Comment by dnlup** [comment]
I can open a PR if you want.

**Comment by fatso83** [comment]
A tiny regression test would be great :)

**Comment by dnlup** [comment]
Should I modify `src` directly ot there is some transpiling that I have missed?

**Comment by benjamingr** [comment]
@dnlup src, PR welcome

**Comment by SimenB** [comment]
> (and run jest in band (--runInBand) if using jest because jest does very "creative" stuff)

(not sure why Jest is brought up when the tests linked in this issue are using Tap, but since it was)

If you have examples where Jest behaves differently in band and not WRT fake timers I'd love to get a bug report with a reproduction. I don't remember having seen any issue about that before

**Comment by benjamingr** [comment]
@SimenB I saw the tests are using both Jest and Tap. 

> If you have examples where Jest behaves differently in band and not WRT fake timers I'd love to get a bug report with a reproduction. I don't remember having seen any issue about that before

This was just a general "in order to debug jest without waiting for the workers to spawn and quickly attaching the debugger to them" tip. I do that when I use Jest and I think (?) it's also the official recommendation at https://jestjs.io/docs/troubleshooting#tests-are-failing-and-you-dont-know-why

On the other hand - I _do_ have a Jest performance issue I'd love to ask you about if you have 20 minutes of your time sometime. What would be a good way to reach out?

**Comment by SimenB** [comment]
Right, when debugging it's easier if you force not using workers (although running a single test will always run in band). I don't think using Node's `worker_threads` and `child_process` APIs necessarily should be classified as "creative" (which is what triggered my response), but that's neither here nor there (and most certainly off topic for this issue 😀).

>What would be a good way to reach out?

Most often by opening an issue, but DM on twitter should be fine in this case 🙂

**Comment by benjamingr** [comment]
Thanks, messaged - this is me :) https://twitter.com/benjamingr_

**Comment by fatso83** [comment]
@benjamingr I updated your Twitter link bio. The underscore was left out when clicking, which made me wonder why you were speaking Spanish 😄 

See same link:
-  https://twitter.com/benjamingr_
- https://twitter.com/benjamingr
