### ISSUE TITLE
Cannot find name 'queueMicrotask'

### ISSUE THREAD

**Issue by minche-tsai** [sinonjs/fake-timers#389]
node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:11:28 - error TS2304: Cannot find name 'queueMicrotask'.

11     queueMicrotask: typeof queueMicrotask;

-   FakeTimers version : v7.1.2
-   Environment : Typescript 9.1.1
-   Other libraries you are using: jest, aws-sdk-client-mock

The package aws-sdk-client-mock is use sinonjs to mock aws-sdk v3. when I use jest to test have this error message.

This article is same problem, but not me.
https://stackoverflow.com/questions/67761159/fake-timers-7-1-x-compile-error-cannot-find-name-queuemicrotask

**Comment by fatso83** [comment]
Due to various issues, we have decided to drop the TS definitions, so a short term fix is to just install fake-timers v6 and the types from DT. See also https://github.com/sinonjs/fake-timers/issues/387#issuecomment-858133528.

**Comment by minche-tsai** [comment]
I has found problem, the queueMicrotask is added in: node.js v11.0.0. But my @types/node is v10.x, so upgrade version was resolved.

**Comment by tomoima525** [comment]
@minche-tsai 

> I has found problem, the queueMicrotask is added in: node.js v11.0.0. But my @types/node is v10.x, so upgrade version was resolved.

this resolved the issue, thanks!
