### ISSUE TITLE
`clearTimeout` will not clear timers created prior to clock installation

### ISSUE THREAD

**Issue by JadenSimon** [sinonjs/fake-timers#406]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

-   FakeTimers version : 8.0.1
-   Environment : node12, macOS Catalina 10.15.7
-   Other libraries you are using: [several](https://github.com/aws/aws-toolkit-vscode/blob/b5af3c53d6720bca08ad603c5e08d30ed5b63804/package.json#L2333), this is happening in tests for a VS Code extension

**What did you expect to happen?**
`clearTimeout` to clear timers even if they weren't created with the mock.

**What actually happens**
The timer that should have been cleared still fires.

**How to reproduce**

> Describe _with code_ how to reproduce the faulty behaviour
> or link to code on JSBin or similar
```js
const timer = setTimeout(() => console.log('This should not be called'), 1);
const clock = FakeTimers.install();
clearTimeout(timer);
clock.uninstall();
// ... wait 1 ms + next event loop
// > 'This should not be called'
```

I can make a PR to fix this if the current behavior is not intended. I added a patch to my own source, though a patch here would be much more robust (need to consider things like duplicate handles, `clearInterval`, `clearImmediate`, etc.)

**Comment by fatso83** [comment]
Closed by #407
