### ISSUE TITLE
ClockDate class overwrite prototype of instance

### ISSUE THREAD

**Issue by Oustinger** [sinonjs/fake-timers#437]
ClockDate class overwrite prototype of instance.
In my real project it happens when I use datepicker library (@eonasdan/tempus-dominus).

-   FakeTimers version : 9.1.2
-   Environment : Opera 89.0.4447.64, Windows 10
-   Example URL : [repository](https://github.com/Oustinger/test_fake-timers_lib)
-   Other libraries you are using: -

**What did you expect to happen?**
I expected to receive instance of DateTime with it's methods

**What actually happens**
Prototype of child instance is not equals to DateTime class, but equals to fake date class

**How to reproduce**
I'd created a [repository](https://github.com/Oustinger/test_fake-timers_lib) with reproducing this problem

i. You can clone and run [project](https://github.com/Oustinger/test_fake-timers_lib)
ii. Or you can create project with @sinonjs/fake-timers and run the code below by yourself

    var FakeTimers = require("@sinonjs/fake-timers");
    
    FakeTimers.install();
    
    class DateTime extends Date {
        constructor() {
            super();
    
            this.bar = 'bar';
        }
    
        foo() {
            console.log('Lorem inpsum');
        }
    }
    
    var dateTime = new DateTime();
    
    dateTime.foo();

**Comment by benjamingr** [comment]
This is probably a bug because when you `new` something in JS and return something different from the constructor - it will return that thing.

```
class Foo {
  constructor() {
     return { x: 5 };
  }
  bar() {} 
}
const f = new Foo();
f.bar(); 
```

We should probably fix the code to not do that _or_ call `Reflect.construct(new.target)` instead of assuming we have a `NativeDate`.

**Comment by fatso83** [comment]
>  when you new something in JS and return something different from the constructor

Where do we do that? I could not see this happening in the example code.

**Comment by benjamingr** [comment]
> Where do we do that? I could not see this happening in the example code.

Our `ClockDate` function doesn't use `this` and instead has a return value even for the case it doesn't return a native date.

**Comment by fatso83** [comment]
@Oustinger The quickest path to seeing a patch commit for this is probably submit a small PR with a regression test. I can make a release quick, but I do not have time atm to debug, fix and verify this.

**Comment by Oustinger** [comment]
@fatso83 I would do that. But I couldn't find a place to fix on my own.

**Comment by fatso83** [comment]
No one would expect you to 🙂 I certainly did not. Do you think you have the hints you need?

**Comment by Oustinger** [comment]
Where is a place in code, where new date's prototype becomes equal to ClockDate?
My debugger can't go deeper [this line](https://github.com/sinonjs/fake-timers/blob/main/src/fake-timers-src.js#L458). What is going on after that?

**Comment by fatso83** [comment]
You cannot get deeper than that function, but the setup of the prototype happens before that

https://github.com/sinonjs/fake-timers/blob/main/src/fake-timers-src.js#L446-L489 covers all the return bits where we create `NativeDate` instances and line 491 is where return our own mirrored constructor. That function call [sets up the prototype](https://github.com/sinonjs/fake-timers/blob/62ad45cfa0479b6ccb9c2dbc06b9620b3f89238e/src/fake-timers-src.js#L424).

> We should probably fix the code to not do that 

Not totally sure how to fix the code myself TBH. ~I am guessing we are invoking NativeDate to create Date objects that are identical in behavior to the NativeDate, and if we were not to invoke `NativeDate` directly I am not sure what to do. ~

This fixed the issue when I tested:
```
                        //return new NativeDate(ClockDate.clock.now);
                        NativeDate.call(this,ClockDate.clock.now);
                        return;
```

Not sure if this is a general fix, but try and see if the test suite works when doing it for all paths :)

**Comment by fatso83** [comment]
I fixed up the last few bits of your original PR and merged it. Thank you a bunch for making it!  I'll close this and release a version 12 shortly.
