### ISSUE TITLE
Test failing since Node 18.8.0

### ISSUE THREAD

**Issue by mroderick** [sinonjs/fake-timers#441]
While working on #439 and #440 with @hexeberlin, we discovered that one unit test is failing since Node 18.8.0

```
  1) FakeTimers
       stubTimers
         should replace the getEntries, getEntriesByX methods with noops that return []:
     TypeError: Cannot assign to read only property 'getEntries' of object '#<Performance>'
      at Context.<anonymous> (test/fake-timers-test.js:3884:50)
      at process.processImmediate (node:internal/timers:471:21)
```

#### How to reproduce

1. `nmv install 18.7`
2. `npm run test-node`
3. Observe all tests pass
1. `nvm install 18.8`
4. `npm run test-node`
5. Observe one test fails

Since this library is downloaded more ~19M times/month and Node 18 has been out for about a month and we have yet to see any error reports about failures in newer Node 18 versions, I think it's safe to say that it's only the test that is failing.

We should fix this soon, as the failing test is preventing us from merging pull requests (or alternatively, we should lock the Node 18 version to 18.7, while we fix this issue).

Plot twist: the tests pass fine in Node v19.0.0

**Comment by fatso83** [comment]
Looking into this. Seems to be some kind of weird runtime issue:
![image](https://user-images.githubusercontent.com/618076/203041065-ad2eb760-9572-4df7-9baf-bb6a8298d75d.png)

Essentially, if _I_ configure the property descriptor in a debugger with the line from the code, it works. If it is just Node running on its own, it has no effect and fails.

```javascript
Object.defineProperty(Performance.prototype, "getEntries", { writable: true })
```

**Comment by fatso83** [comment]
Ha, no, this is just about spelling! I corrected the spelling when doing this. The prop is called `writable`, but we have used `writeable` :rofl:
