### ISSUE TITLE
TypeError Since Node 19

### ISSUE THREAD

**Issue by charlieyeng** [sinonjs/fake-timers#463]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

-   FakeTimers version : `10.0.2`
-   Environment : `macOS Ventura 13.3.1` `Node v20`
-   Other libraries you are using: `"@jest/fake-timers": "^28.1.3"`

**What did you expect to happen?**
I expect the `jest.useFakeTimers()` function to work out of the box.
**What actually happens**
It works for Node v18, but upgrading my stack to Node v19 and beyond  we run into the following errors. 
` TypeError: Cannot assign to read only property 'performance' of object '[object global]'` and
`Can't install fake timers twice on the same global object.`
`jest.useFakeTimers()` is backed by `@sinon/fake-timers` [Jest-Reference](https://jestjs.io/docs/jest-object#fake-timers)
**How to reproduce**
Have the latest node and jest versions installed
```
brew install node 
npm install --save-dev jest
```

and attempt to call `jest.useFakeTimers() ie:
```
jest.useFakeTimers()
```
will result in failures.

Similar issues noted here: [Bug](https://github.com/facebook/react-native/issues/35701) and perhaps related to [this](https://github.com/sinonjs/fake-timers/issues/441)

**Comment by musojames** [comment]
I've run into the same issue with node 19.0.1 on Mac OS Monterrey 12.6

**Comment by mrazauskas** [comment]
> **How to reproduce**
> Have the latest node and jest versions installed

Above you mention that `"@jest/fake-timers": "^28.1.3"` is installed. The latest Jest version `v29.5.0`.

Which one did you actually use? The latest one or `v28`? Did you try upgrading to the latest one?

**Comment by SimenB** [comment]
Duplicate of #438, fwiw
