### ISSUE TITLE
Mock "timers/promise" module

### ISSUE THREAD

**Issue by fatso83** [sinonjs/fake-timers#469]
In #467 @swenzel-arc added the support for the `timers` module in NodeJS. Node also exports a non-callback async/Promise version of that API that needs to be mocked. We can probably very easily piggy-pack on top of the existing work done in the referenced PR. 

Also see the over-arching #418

**Comment by KholdStare** [comment]
Not stale

**Comment by benjamingr** [comment]
This can be closed 🎉
