### ISSUE TITLE
Leave global scope untouched

### ISSUE THREAD

**Issue by bojavou** [sinonjs/fake-timers#472]
-   FakeTimers version : latest, 11.0.0
-   Environment : Linux
-   Example URL : https://github.com/bojavou/fake-timers-crash
-   Other libraries you are using: None

**What did you expect to happen?**

The library loads without mutating the global scope.

**What actually happens**

The library attempts to mutate the global scope on load.

**How to reproduce**

This can be seen with the demo repo.

```sh
$ git clone https://github.com/bojavou/fake-timers-crash.git
$ cd fake-timers-crash
$ npm install
$ node load.js
```

```
/home/user/demo/fake-timers-crash/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:204
        _global.setImmediate = _global.setImmediate;
                             ^

TypeError: Cannot assign to read only property 'setImmediate' of object '#<Object>'
    at withGlobal (/home/user/demo/fake-timers-crash/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:204:30)
    at Object.<anonymous> (/home/user/demo/fake-timers-crash/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:1811:31)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/home/user/demo/fake-timers-crash/load.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
```

**Discussion**

I'm running in a locked down environment with global properties frozen. This causes the library to crash. I see it through loading `sinon` in tests. I'd prefer if the library didn't touch the global scope unless I requested it.

On load there's a `defaultImplementation` [constructed around the global scope](https://github.com/sinonjs/fake-timers/blob/a111a715c76542b15f4701ad8b1752789f597868/src/fake-timers-src.js#L1811C1-L1811C56).

```js
const defaultImplementation = withGlobal(globalObject);
```

The `withGlobal()` function [writes to `setImmediate` and `clearImmediate`](https://github.com/sinonjs/fake-timers/blob/a111a715c76542b15f4701ad8b1752789f597868/src/fake-timers-src.js#L204).

```js
if (setImmediatePresent) {
    _global.setImmediate = _global.setImmediate;
    _global.clearImmediate = _global.clearImmediate;
}
```

I'm not sure what the intention here is. The value is read and assigned to the same place. These look like they should be noops to me, but maybe there's some setter magic. Could these be safely removed? I'm willing to submit a patch if someone knows the right solution.

**Comment by fatso83** [comment]
You can have a look at the got log, but AFAIK this is a workaround for an old peculiarity with Internet Explorer. You needed to do this seemingly pointless song and dance to be able to mutate it later (or something of that sorts). 

As we no longer support IE, only evergreen browsers, this and other hacks like it, can be removed by anyone willing to provide the PR. So feel free ✌️

**Comment by benjamingr** [comment]
I think this was fixed in https://github.com/sinonjs/fake-timers/pull/477 ?

**Comment by fatso83** [comment]
Still need to release a new version, though :)

**Comment by fatso83** [comment]
Verified to have been fixed:
```
carlerik at MacBook-Pro in ~/dev/fake-timers (main)
$ npm link

added 1 package, and audited 3 packages in 1s

found 0 vulnerabilities
Reshimming asdf nodejs...

carlerik at MacBook-Pro in ~/dev/fake-timers (main)
$ cd ../fake-timers-crash/

carlerik at MacBook-Pro in ~/dev/fake-timers-crash (main)
$ cat package.json
{
  "dependencies": {
    "@sinonjs/fake-timers": "^11.0.0"
  }
}

carlerik at MacBook-Pro in ~/dev/fake-timers-crash (main)
$ npm link @sinonjs/fake-timers

removed 2 packages, changed 1 package, and audited 3 packages in 763ms

found 0 vulnerabilities

carlerik at MacBook-Pro in ~/dev/fake-timers-crash (main)
$ cat ../testscript.sh
git clone https://github.com/bojavou/fake-timers-crash.git
cd fake-timers-crash
npm install
node load.js

carlerik at MacBook-Pro in ~/dev/fake-timers-crash (main)
$ node load.js
```

**Comment by bojavou** [comment]
Nice! Thank you guys. Had this on my list but I lost a hard drive and got pulled away from everything to rebuild / get better backups running. Finally close to functional again.
