### ISSUE TITLE
Support performance.measure method

### ISSUE THREAD

**Issue by CreativeTechGuy** [sinonjs/fake-timers#493]
-   FakeTimers version : 11.2.2
-   Environment : Windows 11
-   Example URL : N/A
-   Other libraries you are using: Playwright (but should be irrelevant)

**What did you expect to happen?**

Faking timers with default settings (which will fake `performance`) should fake all of the performance methods including `performance.mark`, `performance.measure`, etc.

**What actually happens**

These methods exist and can be called, but seem to do nothing since calling `performance.measure()` returns `undefined` which isn't a valid return value and then the code crashes when trying to access the properties which are expected to exist on the result.

**How to reproduce**

```
const FakeTimers = await import("https://esm.sh/@sinonjs/fake-timers@11.2.2");
FakeTimers.install();
performance.mark("start");
performance.mark("end");
const measurement = performance.measure("duration", "start", "end");
console.log("duration is", measurement.duration); // Crashes here since measurement is undefined
```

**Comment by fatso83** [comment]
@CreativeTechGuy See if #499 does what you want. It just implements dummies, but your example no longer breaks.

**Comment by CreativeTechGuy** [comment]
Looks like it does it! Thanks 😀
