### ISSUE TITLE
Dates created before useFakeTimers aren't seen as instanceof Date anymore

### ISSUE THREAD

**Issue by erossignon** [sinonjs/fake-timers#504]
-   FakeTimers version : @sinonjs/fake-timers@13.0.1
-   Environment : nodejs
-   Example URL : 
-   Other libraries you are using: node-opcua, sinon@19.0.0

**What did you expect to happen?**

Date object that have been created before fakeTimer takes actions should still be instanceof Date, as it used to be in previous versions

**What actually happens**

**How to reproduce**

npm install sinon@19

```javascript
 import sinon from "sinon";


 // defined before useFakeTimers
 const minDate = new Date(Date.UTC(1601, 0, 1, 0, 0, 0));
 console.log("minDate instanceof Date (before)", minDate instanceof Date);
 const clock = sinon.useFakeTimers();
 const d = new Date();
 console.log("instanceof Date", d instanceof Date);

 console.log("minDate instanceof Date (after) : should be true but is : ", minDate instanceof Date);

 clock.restore();
```

```javascript
// without using sinon
import FakeTimers from "@sinonjs/fake-timers";

// emulating what sinonjs is doing:
function createClock(config, globalCtx) {
    let FakeTimersCtx = FakeTimers;
    if (globalCtx !== null && typeof globalCtx === "object") {
        FakeTimersCtx = FakeTimers.withGlobal(globalCtx);
    }
    const clock = FakeTimersCtx.install(config);
    clock.restore = clock.uninstall;
    return clock;
}

 // defined before useFakeTimers
 const minDate = new Date(Date.UTC(1601, 0, 1, 0, 0, 0));
 console.log("minDate instanceof Date (before)", minDate instanceof Date);
 
var clock = createClock();
 const d = new Date();
 console.log("instanceof Date", d instanceof Date);

 console.log("minDate instanceof Date (after) : should be true but is : ", minDate instanceof Date);

 clock.restore();

```

**Comment by fatso83** [comment]
While this is a difference, I am not sure this is a _bug_ or something we should fix up. The change was published as a breaking change, and _usually_ you would install the fake timers before running the tests, run the tests, and then restore things. This would be an issue if you create data used in the tests before installing fake timers, and I am not sure if that's something that is more important to support than the subclassing case, which seems like a more real use case to support.

Thoughts?

**Comment by erossignon** [comment]
also, in some cases, we may have well-defined dates that are global const.
sometime we need to test that a variant value is of type Date

 ̀`if (variant instanceof Date) { doSomethingWithDate(variant as Date) }`

**Comment by fatso83** [comment]
Try the latest 19.0.2 version of Sinon. It should have the fix.

**Comment by erossignon** [comment]
Awesome solution , thanks, 
I offer you PR #506 with the missing unit-test.

**Comment by fatso83** [comment]
The test was beautiful, but was already covered: I only linked to the specific commit above that had the fix and the test was in a previous commit. You can see it here:

https://github.com/sinonjs/fake-timers/commit/ae0a2665c68576387452dda1abae7425c1779416#diff-5a5796b4730f7629082606dc9407d4b8a084ab5ec38803e6141743b4bbb9f7efR3373
