### ISSUE TITLE
Not resilient to modification of globals 

### ISSUE THREAD

**Issue by dubzzz** [sinonjs/fake-timers#516]
The library does not resist destructive changes of the globals. As I initially reported the issue at https://github.com/vitest-dev/vitest/issues/7024 I wanted to make you aware of the problem.

One fix, if you consider that it should be fixed, would be to capture the globals for Intl and Date when the code got imported.

Feel free to close, if the behavior is expected.

---

_If the suggestion is relevant I can propose a fix._

**Comment by fatso83** [comment]
This is absolutely true and we have done similar changes in the main Sinon project to prevent pollution to globals (like methods on the Array.prototype) affecting us. If you want to supply a fix, it should just be a handful of lines.

**Comment by fatso83** [comment]
Meh

**Comment by dubzzz** [comment]
Arf strange! Sorry for the inconvenience, I'll have to rework it

**Comment by dubzzz** [comment]
Please feel free to revert in case it's blocking you. I'll try to do my best to have something soon

**Comment by fatso83** [comment]
So weird. Works locally:
```
 npx mocha --timeout 200 test/ integration-test/  -R dot --check-leaks
```

**Comment by fatso83** [comment]
Ah, works in Node 20. Fails in Node 22.12.0

**Comment by fatso83** [comment]
Sorry, this is not on you. This is from #515

**Comment by fatso83** [comment]
I did not notice this had failed on merge: https://github.com/sinonjs/fake-timers/commits/main/

**Comment by fatso83** [comment]
Found the issue: #518
